### ISSUE TITLE
Server error when using `service.search`

### ISSUE THREAD

**Issue by TomWagg** [rubin-dp0/tutorial-notebooks#116]
I think it is probably just because I entered a strange query to get the size of the _entire_ table (for Eric Bellm's homework at UW) but I got a 500 server error after some time of running this. Here's the query I ran

```
%%time
results = service.search("SELECT count(coord_ra)"
                         "FROM dp02_dc2_catalogs.Object "
                         "WHERE detect_isPrimary = 1").to_table()
print(results['count'])
```
This ran for about 5 minutes and then here's the error that I got

![image](https://user-images.githubusercontent.com/21990332/212438440-553589a5-f55c-4cf8-97f1-ebba194181cf.png)

And that then resulted in `DALServiceError: 500 Server Error`

**Comment by MelissaGraham** [comment]
Hi @TomWagg, I'm so sorry I didn't see this, we don't use Issues in this repo (only the Support repo). Is this still a problem?

**Comment by MelissaGraham** [comment]
Just to follow-up, the following worked ok for me without timing out, so I'm going to close this issue.

```
center_coords = "62, -37"
results = service.search("SELECT count(coord_ra)"
                         "FROM dp02_dc2_catalogs.Object "
                         "WHERE CONTAINS(POINT('ICRS', coord_ra, coord_dec), "
                         f"CIRCLE('ICRS', {center_coords}, {radius_deg})) = 1 "
                         "AND detect_isPrimary = 1 ").to_table()
print(results['count'])
```
