### ISSUE TITLE
Defined but not used variables

### ISSUE THREAD

**Issue by astrobatty** [rubin-dp0/tutorial-notebooks#23]
Hi,

In `02_Intermediate_TAP_Query.ipynb` there are two (multiple times) defined but not used variables, ``hover_tool`` and ``TOOLS``. Modifying them has no effect on the tutorial, which might be confusing for non-experts.

**Comment by MelissaGraham** [comment]
Thanks @astrobatty, this issue was also reported in https://github.com/rubin-dp0/Support/issues/5#issuecomment-884537562, so I've made a note of this issue in that issue's thread, and will close this issue.
