### ISSUE TITLE
Some notebooks not working?

### ISSUE THREAD

**Issue by emilianomerlin** [rubin-dp0/tutorial-notebooks#42]
Hello,
I logged in to my JupyterLab repo after the summer break to run again the dp0 tutorial notebooks, but I'm currently finding that some of them (1,2,3,6) don't load, giving the following error as I try to load them:

File Load Error for 06_Comparing_Object_and_Truth_Tables.ipynbUnreadable Notebook: /home/emilianomerlin/notebooks/tutorial-notebooks/06_Comparing_Object_and_Truth_Tables.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

(these notebooks don't have a green dot on their side in the left list window, while the others have, and they work)
What should I do?
Thanks,
Cheers
E.

**Comment by ktlim** [comment]
See https://github.com/rubin-dp0/Support/issues/9

**Comment by MelissaGraham** [comment]
And @emilianomerlin  let us know if that solution works for you, or if the issue persists.

**Comment by emilianomerlin** [comment]
It worked, thanks!

**Comment by MelissaGraham** [comment]
Wonderful! Closing this issue.
