### ISSUE TITLE
typo on field `base_localPhotoCalib` in Lightcurve nootebook

### ISSUE THREAD

**Issue by herjy** [rubin-dp0/tutorial-notebooks#62]
In the [09_Single_Star_Lightcurve_with_Butler](https://github.com/rubin-dp0/tutorial-notebooks/blob/6211a9d540f4ece3a8ab062d77c09d014e81c347/09_Single_Star_Lightcurve_with_Butler.ipynb) notebook, `section 3.1 : OPTION A: Retrive source photometry via the Butler (can take ~30 minutes)` one of the fields is written as 'base_localPhotoCalib' when the correct field name has a capital `L`: 'base_LocalPhotoCalib'.

```
#             mag_arr.append(-2.5 * np.log10(src['base_PsfFlux_instFlux'][sx] * src['base_localPhotoCalib'][sx]) + 31.4)
```

**Comment by MelissaGraham** [comment]
Thanks @herjy ! I'll check it out and get a fix done.

**Comment by MelissaGraham** [comment]
Hi again, I checked it out and `base_localPhotoCalib` is correct, with a lower-case "l". At the RSP deployed at the IDF for DP0, using `base_LocalPhotoCalib` with a capital "L" returns an error.

@herjy , could you tell me when and where you found that lower-case "l" local would not work for you?

**Comment by herjy** [comment]
I found it in the DDF run of DC2 3.1 that Jim processed recently. Not as part of dp0 proper.

**Comment by MelissaGraham** [comment]
OK thanks, that explains the difference. In this case the notebook should stay as lower-case "local" because that notebook only applies to DP0 data.
