### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by kadrlica** [rubin-dp0/tutorial-notebooks#65]
Tim Jenness has noted that we can update our repo name from the opaque URI (`s3://butler-us-central1-dp01`) to the shorthand `dp01`. This would also make it easy to switch to `dp02`.

**Comment by kadrlica** [comment]
Colin says this is actually:
```
Butler(config="dp02", collections="2.2i/runs/DP0.2/v23_0_2/PREOPS-905/step_all")
```

**Comment by MelissaGraham** [comment]
I think this issue can be closed? We're making this change in the new NBs.

**Comment by kadrlica** [comment]
Yeah, sounds good to me.
