### ISSUE TITLE
Comments on butler 04b notebook

### ISSUE THREAD

**Issue by timj** [rubin-dp0/tutorial-notebooks#90]
Sorry if you asked me to review this and I missed the request. I saw the announcement on Slack just now for tomorrow's delegate session and I have some comments that really need to be fixed because they are either unnecessary confusing or set bad habits.

* `Butler(“dp02”, collections=)` is the usual way of instantiating a butler. Making people say `config=` seems unnecessary when we never do it in our code and it's extra typing.
* * In the `queryCollections` example rather than using `*MelissaGraham*` as the wild card example it might be more directly related to the previous line if the example was `2.2i/runs/DP0*`. It's also possible to pass multiple wildcards to the `queryCollections` command.
* Rather than using `queryDatasetTypes` to get a single dataset type, consider using `registry.getDatasetType` since then you don’t have to worry about the generator. Using `next()` to find a single dataset type is a bad precedent (in section 2.2) and confusing.
* `len()` works on a set() so why do `len(list(datasetRefs))`?
* Also do not use `butler.get` with a datasetRef — that’s inefficient. If you have a ref you should always use `butler.getDirect`. If you run this in a timing loop you will see that get is much slower because it has to query the registry each time before it asks datastore for the answer.
* What's driving the astropy example using `ResourcePath` and `as_local`? If we have large numbers of people wanting to use astropy.io.fits to read our FITS files like this we need to prioritize making Butler give them something like an nddata representation. Having everyone learn to download the FITS files locally so they can inspect individual HDUs may not be ideal.  cc/ @gpdf.
* Note that it is possible for butler to store datasets in disassembled form. This would lead to `getURI` raising an exception. Be very careful when teaching people that there is one dataset corresponding to one file "on disk".
* I don't necessarily like an example which involves people downloading the file locally and then opening it with afw.image.Exposure. That's what butler is actually doing except Butler is using a caching mechanism to make it more efficient in some examples and bypassing butler to get the thing butler would have given you seems like something to avoid. cc/ @ktlim
* Section 3.1.1 -- use getDirect, not get. (this is a general comment for the entire notebook -- you can explain that get is used if you know the dataset type and dataId but don't have the actual dataset ref).
* Section 3.1.1 -- the `visit` record itself in butler already knows everything that you are retrieving from the visitInfo. It's significantly (orders of magnitude) more efficient to ask for the visit record information from a `DatasetRef` (call `expanded` on the return value of `queryDatasets` than to download each FITS file and get the visitInfo. The visit dimension record has the date, exposure time and boresight and also has the region on the sky as a sphgeom region directly so you don't need to download the WCS and bbox. 3.1.1 should either have its focus change or be rewritten.
* Section 3.3.1 it is better to call butler.get twice (once for each component) than to read the entire calexp just to get visitInfo and filter label. This is because it takes a second just to read all the pixel data into the Exposure that is then ignored.
* 3.3.2 might be easier if you used the visit sphgeom region the butler already knows about.

cc/ @TallJimbo

**Comment by MelissaGraham** [comment]
Seen. I will attempt to fix all later today, thanks Tim.

**Comment by timj** [comment]
I understand that modifying the last few sections to use sphgeom regions from the visit record would be more work than could be done before tomorrow. Of course the WCS from the calexp is very accurate whereas the visit record region is derived solely from the Ra/dec from the header so there are definitely cases where `calexp.wcs` is the right thing. `calexp.visitInfo` will though always be returning the same ra/dec that is in the visit dimension record so it all depends what is being attempted.

**Comment by ktlim** [comment]
I agree that in notebooks we should not be explicitly downloading and then re-reading datasets into our own classes.  I can see an argument, however, for downloading and then reading into someone else's class, as we're never going to be able to provide conversions for everything.

**Comment by TallJimbo** [comment]
> What's driving the astropy example using ResourcePath and as_local? If we have large numbers of people wanting to use astropy.io.fits to read our FITS files like this we need to prioritize making Butler give them something like an nddata representation. Having everyone learn to download the FITS files locally so they can inspect individual HDUs may not be ideal.

I suspect all one can really get out of an astropy-loaded `Exposure` FITS file at present is the image, mask, and variance images as Numpy arrays, as their integer origin; everything else would require significant effort to reconstruct.

And if you want to show users how they can get those Numpy arrays, I'd recommend going through an in-memory `Exposure`, letting our code handle the I/O:

```
exposure = butler.getDirect(...)
image = exposure.image.array
mask = exposure.mask.array
variance = exposure.variance.array
(x0, y0) = exposure.getXY0()
```

Of course, that may make it more appropriate for some other notebook instead of this (and perhaps it's already covered elsewhere), but wrapping up that sort of in-memory conversion and extending it to provide astropy representations of more things is what I consider the more likely path towards implementing get-as-astropy either directly in butler or in a convenience library that's given a butler.

**Comment by timj** [comment]
> Of course, that may make it more appropriate for some other notebook instead of this (and perhaps it's already covered elsewhere), but wrapping up that sort of in-memory conversion in a function and extending it to provide astropy representations of more things is what I consider the most likely path towards implementing get-as-astropy either directly in butler or in a convenience library that's given a butler.

My plan is to support:

```python
astropy_thing = butler.getDirect(ref, storageClass="astropy.NDData")
```
to cover the common cases. We already have storage class conversion infrastructure so this would require us to write an `exposure2nddata` helper function somewhere and everything would "just work". The butler side of this is 95% complete (we use it to do on the fly type conversions).

**Comment by timj** [comment]
> I can see an argument, however, for downloading and then reading into someone else's class,

We'd have to be careful about composite disassembly -- people assuming there is only one file on disk because they want to use their own code to read it either means we have to never disassemble or we have to provide a method in butler for downloading all the files, assembling the composite, and then writing it out again as a single file in a temporary location.

**Comment by kadrlica** [comment]
Also seen. I'll take a look tonight.

**Comment by MelissaGraham** [comment]
Changes made so far in branch tickets/PREOPS-1328, just based on Tim's first batch of comments.

- Section 1.2, updated to simply call `butler = dafButler.Butler('dp02', collections='2.2i/runs/DP0.2')`.
- Section 2.1, leaving demo wildcard example as another user (in this case me). Using `2.2i/runs/DP0*` brings up a world of confusion. Leaving a demo of multiple wildcards for later.
- Section 2.2., Replaced `dt = next(registry.queryDatasetTypes('calexp'))` with `dt = registry.getDatasetType('calexp')`.
- Section 2.2, replaced `print(f"Found {len(list(datasetRefs))} detectors")` with `print(f"Found {len(datasetRefs)} detectors")`.
- Section 2.3, replaced `calexp = butler.get(ref)` with `calexp = butler.getDirect(ref)`.
- Section 2.3.1 on URIs has been entirely removed for now, until we can resolve best practices. I've saved it in my cet-dev folder.
- Section 3.1, replaced `calexp = butler.get(ref)` with `calexp = butler.getDirect(ref)`.

The rest will have to wait until >4pm today, when I can get back to it.

**Comment by timj** [comment]
@TallJimbo has pointed out to me that you can go directly from the visit ID to the htm7 pixel without having to do this:

```python
ra, dec = calexp.visitInfo.boresightRaDec
htm_id = pixelization.index(
    lsst.sphgeom.UnitVector3d(
        lsst.sphgeom.LonLat.fromDegrees(ra.asDegrees(), dec.asDegrees())
    )
)
```

If you already know the visit ID then you can use `registry.queryDataIds` to get the htm7 directly from registry. Here's an example using the command line for ci_hsc_gen3 repo to demonstrate it works but using the `queryDataIds` API is easy enough:

```bash
$ butler query-data-ids ../ci_hsc_gen3/DATA htm7 --where "visit = 903334 and skymap = 'discrete/ci_hsc' and instrument = 'HSC' and detector = 20"
 htm7 
------
189473
189475
```

**Comment by kadrlica** [comment]
@timj @TallJimbo will this approach work for an arbitrary ra,dec or is it directly associated with visits? The nice thing about how it is written now is that the user can pop in any ra, dec (the boresight just provides a convenient one).

**Comment by timj** [comment]
The query-data-ids needs to know a visit ID but that does match with the example where you are obtaining an ra,dec from the calexp.visitInfo -- butler registry knows nothing about arbitrary ra,dec locations but it does know about visits. So if your example is saying "if you have a calexp then you can work out the htm pixel like this" then you should be using queryDataIds. If the obtaining of the ra,dec from the calexp is not the point of the demonstration then it might be better for the example to not use an ra,dec specifically associated with a visit.

**Comment by kadrlica** [comment]
What we say in the notebook is: "Find the HTM ID for a desired sky coordinate. Below, the RA and Dec could be user-specified, but here we use the telescope boresight accessed from the calexp retrieved above." I just want to make sure this is true for the solution we present.

**Comment by timj** [comment]
Yeah, the code is fine for the general case but it's linking it to the calexp that is bothering me because you wouldn't use this to get the HTM for the calexp.

**Comment by kadrlica** [comment]
> Section 3.3.1 it is better to call butler.get twice (once for each component) than to read the entire calexp just to get visitInfo and filter label. This is because it takes a second just to read all the pixel data into the Exposure that is then ignored.

This makes total sense, but I think that we are just consistently starting each subsection by grabbing the same calexp (we do this at the start of 3.2 and 3.3). Obviously there is no reason to grab the same calexp twice, except that the notebooks are dynamic, so we want to make sure that user hasn't change the calexp on us between 3.2 and 3.3 (i.e., by playing around with the visit). I don't think we actually care about the visit info or filter, so we could remove these lines if they are confusing.

**Comment by timj** [comment]
> starting each subsection by grabbing the same calexp

Okay. I imagine that's fine, but I worry that we are training people to do the inefficient thing if they only want a component. Maybe if there was a section about retrieving components that talked about this, that would stop me worrying. Reading 100MB of pixel data into an Exposure that is not needed is always going to be slower, even on a local file system, if the user of the notebook does not want the pixel data.

**Comment by kadrlica** [comment]
Yeah, that sounds reasonable. In an intro notebook I'd be concerned about confusing people, but here I think it will work. I think in 3.2 and 3.3, we should just be explicit about grabbing only the visitInfo and explaining why we are doing that.

**Comment by timj** [comment]
> As a note, grabbing the visitInfo takes about half as long (0.882s vs 1.83s).

Yes, so about a second of overhead to read in all the pixel data.

**Comment by kadrlica** [comment]
Summarizing my commits for a handover to @MelissaGraham...

> Section 3.3.1 it is better to call butler.get twice (once for each component) than to read the entire calexp just to get visitInfo and filter label. This is because it takes a second just to read all the pixel data into the Exposure that is then ignored.

*  I've changed to grabbing just the calexp.visitInfo rather than the full calexp in Section 3.2 and Section 3.3.1.

> 3.3.2 might be easier if you used the visit sphgeom region the butler already knows about.

* Since we intend the technique to be valid for an arbitrary ra,dec, I have _not_ modified how we are doing the sphgeom lookup in Section 3.3.2.

> use getDirect, not get

* I've changed the section title in Section 2.3 and added some text explaining why we are using `Butler.getDirect`.

> Section 3.1.1 -- the visit record itself in butler already knows everything that you are retrieving from the visitInfo. It's significantly (orders of magnitude) more efficient to ask for the visit record information from a DatasetRef (call expanded on the return value of queryDatasets than to download each FITS file and get the visitInfo. The visit dimension record has the date, exposure time and boresight and also has the region on the sky as a sphgeom region directly so you don't need to download the WCS and bbox. 3.1.1 should either have its focus change or be rewritten.

* I didn't understand the suggested change here, and I think a rewrite is probably beyond the scope for tomorrow.

**Comment by timj** [comment]
I was not expecting the last section to be changed significantly given the time constraints. In summary though:

If you call `.expanded()` on the return value of `queryDatasets()` you will get `DatasetRef` results that have a full expanded data coordinate. You can then ask directly for the record information.

Something like this:

```python
refs = butler.registry.queryDatasets("calexp", collections=...).expanded()

for ref in refs:
    record = ref.dataId.records["visit"]
    print(record.id, record.exposure_time, record.timespan, record.region)
```
The region is the full visit region, not the per-detector region. You can print the `record` itself to see what is there. The tracking_ra and tracking_dec are not forwarded to visit (the region being there already, although you can ask for az/el) but are in the `exposure` record. You can map from visit back to exposure using the `visit_definition` table and `queryDimensionRecords` and there is also `visit_detector_region` to get the regions for each detector for each visit.

**Comment by gpdf** [comment]
I was pinged above, and I'm sorry I was not able to review this carefully myself right away, but I agree with the entire thrust of the feedback @timj provided.  It is a risk of doing this "previews" that we expose people to things that won't exist or work in the real system, and it is easy to imagine people replicating unsustainable or inefficient things.  We want to make sure that DP0.1-isms and Gen2-isms and other such things are minimally propagated.  At some level we can never get these cats back in the bag, since people copy code (and we are, in effect, encouraging them to).

I really appreciate both @timj's time in reviewing this and the CET's in responding quickly.

**Comment by MelissaGraham** [comment]
After Alex's updates, just one more in tickets/PREOPS-1328.

Section 3.1.1 - added a demonstration of the use of .expanded with queryDatasets().

Merging our branches and releasing the updated version of NB04b to prod now. I think that incorporates all of the requests with the exception of sphgeom, which Alex addressed above with a comment?

I'll let the reporter, @timj close this issue.

**Comment by kadrlica** [comment]
> ```python
> record = ref.dataId.records["visit"]
> ```

Thanks, this is what I was missing!
